version: '3.4'
app:
  build: ./app
services:
  aspnetcorethingsserver:
    image: ${DOCKER_REGISTRY}aspnetcorethingsserver
    build:
      context: .
      dockerfile: src\AspNetCoreThingsServer\Dockerfile
